// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTZ3FtidYmmLyhonTyBjhXt18zHFgRPUc',
    appId: '1:888859683899:web:fe6eb1a295127442eb401e',
    messagingSenderId: '888859683899',
    projectId: 'quiz-app-63699',
    authDomain: 'quiz-app-63699.firebaseapp.com',
    storageBucket: 'quiz-app-63699.appspot.com',
    measurementId: 'G-1EZW1DDD9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiC94zyGzT7rTFLklZLfBhURYMUTEd_SQ',
    appId: '1:888859683899:android:a485e2d957ab861beb401e',
    messagingSenderId: '888859683899',
    projectId: 'quiz-app-63699',
    storageBucket: 'quiz-app-63699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ1KuTWNnpjrVrVTk1xr1Trt_6RrHRS7w',
    appId: '1:888859683899:ios:5598cd645261c7fbeb401e',
    messagingSenderId: '888859683899',
    projectId: 'quiz-app-63699',
    storageBucket: 'quiz-app-63699.appspot.com',
    iosBundleId: 'com.example.flashcardQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ1KuTWNnpjrVrVTk1xr1Trt_6RrHRS7w',
    appId: '1:888859683899:ios:da96c77bd75edb75eb401e',
    messagingSenderId: '888859683899',
    projectId: 'quiz-app-63699',
    storageBucket: 'quiz-app-63699.appspot.com',
    iosBundleId: 'com.example.flashcardQuizApp.RunnerTests',
  );
}
